lookup_gps:
  name: Lookup GPS
  description: List gas prices based on GPS coordinates of device tracker.
  target:
    entity:
      domain: 
        - device_tracker
        - person

lookup_zip:
  name: Lookup Zip
  description: List gas prices based on entered ZIP code.
  target:
    text:
    